<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/logo_ciencia_datos.png">

<center><h1 style="font-size:2em;color:#2467C0"> Pandas y GLOB  </h1></center>

<center><h2 style="font-size:2em;color:#840700">   Manipulación de archivos con GLOB </h4></center>

<br>
<table>
<col width="250">
<col width="750">
<tr>
<td><img src="figuras/glob.png" align="left" style="width:150px"/></td>
<td>

La función **glob.glob()** devuelve una lista con las entradas que coincidan con el patrón especificado en *pathname*.

**glob.glob( *pathname* , recursive=False)** 
    
<br>
</td>
</tr>
</table>

## Integrantes

Nombre 1:

Nombre 2:

# Librerías

Cargando las bibliotecas que necesitamos

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

## Mostrando todos los archivos de "/datos"

La salida serán los archivos en forma de lista

In [3]:
# establecer ruta de búsqueda  
path = 'datos'
files = glob.glob(path + '/*') #The "*" gives all files 
files

['datos\\informacion.txt',
 'datos\\semestre1a.csv',
 'datos\\semestre1b.csv',
 'datos\\semestre1c.csv',
 'datos\\semestre2a.csv',
 'datos\\semestre2b.csv',
 'datos\\semestre2c.csv',
 'datos\\semestre3a.csv',
 'datos\\semestre3b.csv',
 'datos\\semestre3c.csv',
 'datos\\semestres.txt',
 'datos\\Ventas']

## Mostrando  los archivos  **.txt** de "/datos"

La salida serán los archivos .txt en forma de lista

In [4]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos txt  
path = 'datos'
files = glob.glob(path + '/*.txt')
files

['datos\\informacion.txt', 'datos\\semestres.txt']

## Mostrando  los archivos .csv de "/datos"

La salida serán los archivos .csv en forma de lista

In [5]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/*.csv')
files

['datos\\semestre1a.csv',
 'datos\\semestre1b.csv',
 'datos\\semestre1c.csv',
 'datos\\semestre2a.csv',
 'datos\\semestre2b.csv',
 'datos\\semestre2c.csv',
 'datos\\semestre3a.csv',
 'datos\\semestre3b.csv',
 'datos\\semestre3c.csv']

## Concatenando todos los archivos .csv para formar un dataframe

In [7]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/*.csv')
print(files)
# crear una lista vacía para almacenar  los dataframes
list_files = []
# recorrer la lista de archivos para crear la lista de archivos 
for file in files:
    temp_df = pd.read_csv(file)
    #print(temp_df.shape)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

['datos\\semestre1a.csv', 'datos\\semestre1b.csv', 'datos\\semestre1c.csv', 'datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre2c.csv', 'datos\\semestre3a.csv', 'datos\\semestre3b.csv', 'datos\\semestre3c.csv']

     NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0   ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1    AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2     MARTA      BALAM            94  MECATRONICA    MERIDA
3     JULIA      ORTIZ            86   RENOVABLES      UMAN
4   PASCUAL        MAY            58       FISICA    MERIDA
..      ...        ...           ...          ...       ...
0    ISABEL       RUIZ            89  MECATRONICA    MERIDA
1    MARTIN       CANO            99       FISICA     TICUL
2      RICK    SANCHEZ           100       FISICA    MERIDA
3     CARLA   MORRISON            94       FISICA  PROGRESO
4     PEDRO      MARIN            98  MECATRONICA    MERIDA

[69 rows x 5 columns]

## Concatenando los archivos .csv del primer semestre 

El comodín * representa desde nada, hasta cualquier cantidad de caracteres y dígitos

In [9]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre1*.csv') # the "*" for the rest of the file names that interest me
# Quick note : "*" for werever nomber of characters and "?" just for one character 
#print(files)
# crear una lista vacía para almacenar los dataframes
list_files = []
# recorrer la lista de archivos para crear la lista de archivos 
for file in files:
    temp_df = pd.read_csv(file)
   # print(temp_df.shape)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0     ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1      AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2       MARTA      BALAM            94  MECATRONICA    MERIDA
3       JULIA      ORTIZ            86   RENOVABLES      UMAN
4     PASCUAL        MAY            58       FISICA    MERIDA
5       PEDRO      GOMEZ            85       FISICA    MERIDA
6     ENRIQUE        GIL            89  MECATRONICA  PROGRESO
7       PEDRO    ALARCON            99   RENOVABLES   KANASIN
8         ANA  HERNANDEZ            89       FISICA   KANASIN
9      MANUEL   GONZALEZ            92       FISICA  PROGRESO
0    CRISTINA     VALERO            84  MECATRONICA    MERIDA
1        JUAN      BALAM           100       FISICA     MOTUL
2       LUCIA    SERRANO            60       FISICA    MERIDA
3       PILAR        GIL            88   RENOVABLES     MOTUL
4      ALICIA      BALAM            85   RENOVABLES    MERIDA
5      MANUEL    RODENAS            12   RENOVABLES    MERIDA
6       LUCIA  CABALLERO            85  MECATRONICA    MERIDA
7   ASCENSION         EK            86  MECATRONICA      UMAN
8        RAUL     TORRES            52  MECATRONICA    MERIDA
9       JESUS  FERNANDEZ            60  MECATRONICA    MERIDA
10     RAQUEL     CUENCA            82  MECATRONICA    MERIDA
0      ISMAEL     LOZANO            98  MECATRONICA    MERIDA
1       ROCIO   BLAZQUEZ            82   RENOVABLES    MERIDA
2        ROSA      TEBAR            75  MECATRONICA    MERIDA
3     MANUELA     ORTEGA            95  MECATRONICA    MERIDA
4       MARIA   MARTINEZ            95       FISICA    MERIDA
5       MARIA       CANO            92       FISICA  PROGRESO
6      JOSEFA      LOPEZ            98  MECATRONICA    MERIDA
7        LUIS     ALFARO            65       FISICA    MERIDA
8     ALBERTO      PEREZ            63  MECATRONICA    MERIDA
9   FRANCISCO       PECH            96       FISICA    MERIDA
10        ANA    NAVARRO            59  MECATRONICA    MERIDA

## Concatenando los archivos .csv del primer y segundo semestre 

El comodín **[ ]**  representa un rango,  ya sea de caracteres o de números.

In [11]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre[1-2]*.csv') #The "[]" for a range of number if in the files name have a number of interes 
print(files)
# crear una lista vacía para almacenar  los dataframes
list_files = []
# recorrer la lista de archivos para crear la lista de archivos 
for file in files:
    temp_df = pd.read_csv(file)
    #print(temp_df.shape)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

['datos\\semestre1a.csv', 'datos\\semestre1b.csv', 'datos\\semestre1c.csv', 'datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre2c.csv']

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0     ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1      AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2       MARTA      BALAM            94  MECATRONICA    MERIDA
3       JULIA      ORTIZ            86   RENOVABLES      UMAN
4     PASCUAL        MAY            58       FISICA    MERIDA
5       PEDRO      GOMEZ            85       FISICA    MERIDA
6     ENRIQUE        GIL            89  MECATRONICA  PROGRESO
7       PEDRO    ALARCON            99   RENOVABLES   KANASIN
8         ANA  HERNANDEZ            89       FISICA   KANASIN
9      MANUEL   GONZALEZ            92       FISICA  PROGRESO
0    CRISTINA     VALERO            84  MECATRONICA    MERIDA
1        JUAN      BALAM           100       FISICA     MOTUL
2       LUCIA    SERRANO            60       FISICA    MERIDA
3       PILAR        GIL            88   RENOVABLES     MOTUL
4      ALICIA      BALAM            85   RENOVABLES    MERIDA
5      MANUEL    RODENAS            12   RENOVABLES    MERIDA
6       LUCIA  CABALLERO            85  MECATRONICA    MERIDA
7   ASCENSION         EK            86  MECATRONICA      UMAN
8        RAUL     TORRES            52  MECATRONICA    MERIDA
9       JESUS  FERNANDEZ            60  MECATRONICA    MERIDA
10     RAQUEL     CUENCA            82  MECATRONICA    MERIDA
0      ISMAEL     LOZANO            98  MECATRONICA    MERIDA
1       ROCIO   BLAZQUEZ            82   RENOVABLES    MERIDA
2        ROSA      TEBAR            75  MECATRONICA    MERIDA
3     MANUELA     ORTEGA            95  MECATRONICA    MERIDA
4       MARIA   MARTINEZ            95       FISICA    MERIDA
5       MARIA       CANO            92       FISICA  PROGRESO
6      JOSEFA      LOPEZ            98  MECATRONICA    MERIDA
7        LUIS     ALFARO            65       FISICA    MERIDA
8     ALBERTO      PEREZ            63  MECATRONICA    MERIDA
9   FRANCISCO       PECH            96       FISICA    MERIDA
10        ANA    NAVARRO            59  MECATRONICA    MERIDA
0    CONSUELO       PECH            83   RENOVABLES    MERIDA
1       ELENA   CASTILLO            73  MECATRONICA    MERIDA
2      JAVIER      PEREZ            57   RENOVABLES    MERIDA
3     ANGELES       DIAZ            80  MECATRONICA    MERIDA
4       MARIO    RAMIREZ            89       FISICA    MERIDA
5       PILAR    SERRANO            87   RENOVABLES   KANASIN
6      MIGUEL    JIMENEZ            80   RENOVABLES    MERIDA
0        ROSA   MORCILLO            93  MECATRONICA    MERIDA
1        JUAN     ARENAS            47       FISICA    MERIDA
2      DANIEL     ROMERO            98   RENOVABLES    MERIDA
3      RAFAEL        MAY            87  MECATRONICA    MERIDA
4       PABLO     MOLINA            86  MECATRONICA    MERIDA
5       MARIA      MARIN            86       FISICA    MERIDA
6       MARIA     GARCIA            96       FISICA    MERIDA
0      ALVARO      ORTIZ            89  MECATRONICA    MERIDA
1      ISABEL    SANCHEZ            96   RENOVABLES    MERIDA
2         ANA    ALARCON            84       FISICA  PROGRESO
3       ANGEL   MORCILLO            98  MECATRONICA    MERIDA
4       JESUS     ORTEGA            74  MECATRONICA    MERIDA
5       RAMON    GARRIDO            87  MECATRONICA     MOTUL
6     VICENTE  CABALLERO             8  MECATRONICA    MERIDA

## Concatenando los archivos .csv de los grupos "a"
El comodín **?** Representa un único carácter.

In [25]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre?a.csv')
print(files)
# crear una lista vacía para almacenar  los dataframes
list_files = []
# recorrer la lista de archivos para crear la lista de archivos 
for file in files:
    temp_df = pd.read_csv(file)
    print(temp_df.shape)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

['datos\\semestre1a.csv', 'datos\\semestre2a.csv', 'datos\\semestre3a.csv']
(10, 5)
(7, 5)
(5, 5)

     NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0   ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1    AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2     MARTA      BALAM            94  MECATRONICA    MERIDA
3     JULIA      ORTIZ            86   RENOVABLES      UMAN
4   PASCUAL        MAY            58       FISICA    MERIDA
5     PEDRO      GOMEZ            85       FISICA    MERIDA
6   ENRIQUE        GIL            89  MECATRONICA  PROGRESO
7     PEDRO    ALARCON            99   RENOVABLES   KANASIN
8       ANA  HERNANDEZ            89       FISICA   KANASIN
9    MANUEL   GONZALEZ            92       FISICA  PROGRESO
0  CONSUELO       PECH            83   RENOVABLES    MERIDA
1     ELENA   CASTILLO            73  MECATRONICA    MERIDA
2    JAVIER      PEREZ            57   RENOVABLES    MERIDA
3   ANGELES       DIAZ            80  MECATRONICA    MERIDA
4     MARIO    RAMIREZ            89       FISICA    MERIDA
5     PILAR    SERRANO            87   RENOVABLES   KANASIN
6    MIGUEL    JIMENEZ            80   RENOVABLES    MERIDA
0      JUAN    CEBRIAN            85       FISICA    MERIDA
1      JOSE    COLLADO            96       FISICA  PROGRESO
2   ANTONIA  RODRIGUEZ            83   RENOVABLES    MERIDA
3      LUIS      PEREZ            70  MECATRONICA     MOTUL
4  FERNANDO    CAMACHO            90   RENOVABLES    MERIDA

## Concatenando los archivos .csv de los grupos "a" y "b"

El comodín **[ ]**  representa un rango,  ya sea de caracteres o de números.

In [32]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files =  glob.glob(path + '/semestre?[a-b].csv')
print(files)
# crear una lista vacía para almacenar  los dataframes
list_files = []
# recorrer la lista de archivos para crear la lista de archivos 
for file in files:
    temp_df = pd.read_csv(file)
    print(temp_df.shape)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

['datos\\semestre1a.csv', 'datos\\semestre1b.csv', 'datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre3a.csv', 'datos\\semestre3b.csv']
(10, 5)
(11, 5)
(7, 5)
(7, 5)
(5, 5)
(6, 5)

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0     ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1      AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2       MARTA      BALAM            94  MECATRONICA    MERIDA
3       JULIA      ORTIZ            86   RENOVABLES      UMAN
4     PASCUAL        MAY            58       FISICA    MERIDA
5       PEDRO      GOMEZ            85       FISICA    MERIDA
6     ENRIQUE        GIL            89  MECATRONICA  PROGRESO
7       PEDRO    ALARCON            99   RENOVABLES   KANASIN
8         ANA  HERNANDEZ            89       FISICA   KANASIN
9      MANUEL   GONZALEZ            92       FISICA  PROGRESO
0    CRISTINA     VALERO            84  MECATRONICA    MERIDA
1        JUAN      BALAM           100       FISICA     MOTUL
2       LUCIA    SERRANO            60       FISICA    MERIDA
3       PILAR        GIL            88   RENOVABLES     MOTUL
4      ALICIA      BALAM            85   RENOVABLES    MERIDA
5      MANUEL    RODENAS            12   RENOVABLES    MERIDA
6       LUCIA  CABALLERO            85  MECATRONICA    MERIDA
7   ASCENSION         EK            86  MECATRONICA      UMAN
8        RAUL     TORRES            52  MECATRONICA    MERIDA
9       JESUS  FERNANDEZ            60  MECATRONICA    MERIDA
10     RAQUEL     CUENCA            82  MECATRONICA    MERIDA
0    CONSUELO       PECH            83   RENOVABLES    MERIDA
1       ELENA   CASTILLO            73  MECATRONICA    MERIDA
2      JAVIER      PEREZ            57   RENOVABLES    MERIDA
3     ANGELES       DIAZ            80  MECATRONICA    MERIDA
4       MARIO    RAMIREZ            89       FISICA    MERIDA
5       PILAR    SERRANO            87   RENOVABLES   KANASIN
6      MIGUEL    JIMENEZ            80   RENOVABLES    MERIDA
0        ROSA   MORCILLO            93  MECATRONICA    MERIDA
1        JUAN     ARENAS            47       FISICA    MERIDA
2      DANIEL     ROMERO            98   RENOVABLES    MERIDA
3      RAFAEL        MAY            87  MECATRONICA    MERIDA
4       PABLO     MOLINA            86  MECATRONICA    MERIDA
5       MARIA      MARIN            86       FISICA    MERIDA
6       MARIA     GARCIA            96       FISICA    MERIDA
0        JUAN    CEBRIAN            85       FISICA    MERIDA
1        JOSE    COLLADO            96       FISICA  PROGRESO
2     ANTONIA  RODRIGUEZ            83   RENOVABLES    MERIDA
3        LUIS      PEREZ            70  MECATRONICA     MOTUL
4    FERNANDO    CAMACHO            90   RENOVABLES    MERIDA
0      EMILIO      BALAM            85       FISICA    MERIDA
1       JULIA    RODENAS            98       FISICA    MERIDA
2      DANIEL        MAY            98   RENOVABLES    MERIDA
3       RAMON        MAY            87  MECATRONICA    MERIDA
4       PEDRO     MOLINA            96  MECATRONICA    MERIDA
5       LUCIA   MARTINEZ            86       FISICA    MERIDA

# TAREA

<div class="alert alert-success">
<b>EJERCICIO 1: Concatenar todos los archivos  .csv  </b>:

 <ul>
  <li> a) Encontrar el promedio y   desviación estándar  </li>
  <li> b) Datos del estudiante(s) con la calificación más alta </li>   
  <li> c) Datos del estudiante(s) con la calificación más baja </li>  
  <li> d) El nombre que más se repite </li>  
  <li> e) El apellido que más se repite </li>       
     
</ul>
</div>

In [49]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/*.csv')
list_files = []
for file in files:
    temp_df = pd.read_csv(file)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

     NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0   ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1    AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2     MARTA      BALAM            94  MECATRONICA    MERIDA
3     JULIA      ORTIZ            86   RENOVABLES      UMAN
4   PASCUAL        MAY            58       FISICA    MERIDA
..      ...        ...           ...          ...       ...
0    ISABEL       RUIZ            89  MECATRONICA    MERIDA
1    MARTIN       CANO            99       FISICA     TICUL
2      RICK    SANCHEZ           100       FISICA    MERIDA
3     CARLA   MORRISON            94       FISICA  PROGRESO
4     PEDRO      MARIN            98  MECATRONICA    MERIDA

[69 rows x 5 columns]

In [50]:
print(df['CALIFICACION'].mean())
print(df['CALIFICACION'].std())

81.72463768115942
18.72391052196206

In [51]:
#df.groupby('NOMBRE').max()

In [52]:
df.sort_values(by='CALIFICACION', ascending=False).head(1)

  NOMBRE APELLIDO  CALIFICACION CARRERA  CIUDAD
2   RICK  SANCHEZ           100  FISICA  MERIDA

<div class="alert alert-success">
<b>EJERCICIO 2: Concatenar todos los archivos  .csv del primer semestre </b>:

 <ul>
  <li> a) Encontrar el promedio y   desviación estándar  </li>
  <li> b) Datos del estudiante(s) con la calificación más alta </li>   
  <li> c) Datos del estudiante(s) con la calificación más baja </li>   
</ul>
</div>

In [53]:
path = 'datos'
files = glob.glob(path + '/semestre1*.csv') 
#print(files)
list_files = []
for file in files:
    temp_df = pd.read_csv(file) #we read the file and stored the data momentarily in "tem_df"
    list_files.append(temp_df) #we add the read  
df2 = pd.concat(list_files, axis=0)
df2

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0     ENRIQUE     MORENO            40   RENOVABLES    MERIDA
1      AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2       MARTA      BALAM            94  MECATRONICA    MERIDA
3       JULIA      ORTIZ            86   RENOVABLES      UMAN
4     PASCUAL        MAY            58       FISICA    MERIDA
5       PEDRO      GOMEZ            85       FISICA    MERIDA
6     ENRIQUE        GIL            89  MECATRONICA  PROGRESO
7       PEDRO    ALARCON            99   RENOVABLES   KANASIN
8         ANA  HERNANDEZ            89       FISICA   KANASIN
9      MANUEL   GONZALEZ            92       FISICA  PROGRESO
0    CRISTINA     VALERO            84  MECATRONICA    MERIDA
1        JUAN      BALAM           100       FISICA     MOTUL
2       LUCIA    SERRANO            60       FISICA    MERIDA
3       PILAR        GIL            88   RENOVABLES     MOTUL
4      ALICIA      BALAM            85   RENOVABLES    MERIDA
5      MANUEL    RODENAS            12   RENOVABLES    MERIDA
6       LUCIA  CABALLERO            85  MECATRONICA    MERIDA
7   ASCENSION         EK            86  MECATRONICA      UMAN
8        RAUL     TORRES            52  MECATRONICA    MERIDA
9       JESUS  FERNANDEZ            60  MECATRONICA    MERIDA
10     RAQUEL     CUENCA            82  MECATRONICA    MERIDA
0      ISMAEL     LOZANO            98  MECATRONICA    MERIDA
1       ROCIO   BLAZQUEZ            82   RENOVABLES    MERIDA
2        ROSA      TEBAR            75  MECATRONICA    MERIDA
3     MANUELA     ORTEGA            95  MECATRONICA    MERIDA
4       MARIA   MARTINEZ            95       FISICA    MERIDA
5       MARIA       CANO            92       FISICA  PROGRESO
6      JOSEFA      LOPEZ            98  MECATRONICA    MERIDA
7        LUIS     ALFARO            65       FISICA    MERIDA
8     ALBERTO      PEREZ            63  MECATRONICA    MERIDA
9   FRANCISCO       PECH            96       FISICA    MERIDA
10        ANA    NAVARRO            59  MECATRONICA    MERIDA

In [54]:
print(df2['CALIFICACION'].mean())
print(df2['CALIFICACION'].std())

78.34375
20.05574388805426

In [62]:
df2.sort_values(by='CALIFICACION', ascending=False)#.head()

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
1        JUAN      BALAM           100       FISICA     MOTUL
7       PEDRO    ALARCON            99   RENOVABLES   KANASIN
6      JOSEFA      LOPEZ            98  MECATRONICA    MERIDA
0      ISMAEL     LOZANO            98  MECATRONICA    MERIDA
9   FRANCISCO       PECH            96       FISICA    MERIDA
4       MARIA   MARTINEZ            95       FISICA    MERIDA
3     MANUELA     ORTEGA            95  MECATRONICA    MERIDA
2       MARTA      BALAM            94  MECATRONICA    MERIDA
5       MARIA       CANO            92       FISICA  PROGRESO
9      MANUEL   GONZALEZ            92       FISICA  PROGRESO
6     ENRIQUE        GIL            89  MECATRONICA  PROGRESO
8         ANA  HERNANDEZ            89       FISICA   KANASIN
3       PILAR        GIL            88   RENOVABLES     MOTUL
7   ASCENSION         EK            86  MECATRONICA      UMAN
3       JULIA      ORTIZ            86   RENOVABLES      UMAN
4      ALICIA      BALAM            85   RENOVABLES    MERIDA
5       PEDRO      GOMEZ            85       FISICA    MERIDA
6       LUCIA  CABALLERO            85  MECATRONICA    MERIDA
0    CRISTINA     VALERO            84  MECATRONICA    MERIDA
10     RAQUEL     CUENCA            82  MECATRONICA    MERIDA
1       ROCIO   BLAZQUEZ            82   RENOVABLES    MERIDA
2        ROSA      TEBAR            75  MECATRONICA    MERIDA
7        LUIS     ALFARO            65       FISICA    MERIDA
8     ALBERTO      PEREZ            63  MECATRONICA    MERIDA
1      AMPARO  CABALLERO            63   RENOVABLES    MERIDA
2       LUCIA    SERRANO            60       FISICA    MERIDA
9       JESUS  FERNANDEZ            60  MECATRONICA    MERIDA
10        ANA    NAVARRO            59  MECATRONICA    MERIDA
4     PASCUAL        MAY            58       FISICA    MERIDA
8        RAUL     TORRES            52  MECATRONICA    MERIDA
0     ENRIQUE     MORENO            40   RENOVABLES    MERIDA
5      MANUEL    RODENAS            12   RENOVABLES    MERIDA

In [59]:
#df2['CALIFICACION'].sort_values(ascending=False).head(1)

In [48]:
path = 'datos'
files = glob.glob(path + '/semestre1*.csv') 
#print(files)
list_filesmax = []
for file in files:
    temp_df = pd.read_csv(file) #we read the file and stored the data momentarily in "tem_df"
    max_cal= temp_df.sort_values(by='CALIFICACION', ascending=False).head(1)
    #print(max_cal)
    list_filesmax.append(max_cal) #we add the read  
dfmax = pd.concat(list_filesmax, axis=0)
dfmax

   NOMBRE APELLIDO  CALIFICACION      CARRERA   CIUDAD
7   PEDRO  ALARCON            99   RENOVABLES  KANASIN
1    JUAN    BALAM           100       FISICA    MOTUL
0  ISMAEL   LOZANO            98  MECATRONICA   MERIDA

In [57]:
path = 'datos'
files = glob.glob(path + '/semestre1*.csv') 
#print(files)
list_filesmin = []
for file in files:
    temp_df = pd.read_csv(file) #we read the file and stored the data momentarily in "tem_df"
    max_cal= temp_df.sort_values(by='CALIFICACION', ascending=True).head(1)
    #print(max_cal)
    list_filesmin.append(max_cal) #we add the read  
dfmin = pd.concat(list_filesmin, axis=0)
dfmin

     NOMBRE APELLIDO  CALIFICACION      CARRERA  CIUDAD
0   ENRIQUE   MORENO            40   RENOVABLES  MERIDA
5    MANUEL  RODENAS            12   RENOVABLES  MERIDA
10      ANA  NAVARRO            59  MECATRONICA  MERIDA

<div class="alert alert-success">
<b>EJERCICIO 3: Concatenar todos los archivos .csv de los grupos "c", es decir semestre1c, semestre2c y semestre3c </b>:

 <ul>
  <li> a) Encontrar el promedio y   desviación estándar  </li>
  <li> b) Datos del estudiante(s) con la calificación más alta </li>   
  <li> c) Datos del estudiante(s) con la calificación más baja </li>   
</ul>
</div>

In [64]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre?c.csv')
print(files)
list_files = [] 
for file in files:
    temp_df = pd.read_csv(file)
    list_files.append(temp_df)
df = pd.concat(list_files, axis=0)
df

['datos\\semestre1c.csv', 'datos\\semestre2c.csv', 'datos\\semestre3c.csv']

       NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0      ISMAEL     LOZANO            98  MECATRONICA    MERIDA
1       ROCIO   BLAZQUEZ            82   RENOVABLES    MERIDA
2        ROSA      TEBAR            75  MECATRONICA    MERIDA
3     MANUELA     ORTEGA            95  MECATRONICA    MERIDA
4       MARIA   MARTINEZ            95       FISICA    MERIDA
5       MARIA       CANO            92       FISICA  PROGRESO
6      JOSEFA      LOPEZ            98  MECATRONICA    MERIDA
7        LUIS     ALFARO            65       FISICA    MERIDA
8     ALBERTO      PEREZ            63  MECATRONICA    MERIDA
9   FRANCISCO       PECH            96       FISICA    MERIDA
10        ANA    NAVARRO            59  MECATRONICA    MERIDA
0      ALVARO      ORTIZ            89  MECATRONICA    MERIDA
1      ISABEL    SANCHEZ            96   RENOVABLES    MERIDA
2         ANA    ALARCON            84       FISICA  PROGRESO
3       ANGEL   MORCILLO            98  MECATRONICA    MERIDA
4       JESUS     ORTEGA            74  MECATRONICA    MERIDA
5       RAMON    GARRIDO            87  MECATRONICA     MOTUL
6     VICENTE  CABALLERO             8  MECATRONICA    MERIDA
0      ISABEL       RUIZ            89  MECATRONICA    MERIDA
1      MARTIN       CANO            99       FISICA     TICUL
2        RICK    SANCHEZ           100       FISICA    MERIDA
3       CARLA   MORRISON            94       FISICA  PROGRESO
4       PEDRO      MARIN            98  MECATRONICA    MERIDA

In [65]:
print(df['CALIFICACION'].mean())
print(df['CALIFICACION'].std())

84.08695652173913
20.676981148299056

In [67]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre?c.csv')
print(files)
list_filesmax = [] 
for file in files:
    temp_df = pd.read_csv(file)
    max_cal= temp_df.sort_values(by='CALIFICACION', ascending=False).head(1)
    list_filesmax.append(max_cal)
dfmax = pd.concat(list_filesmax, axis=0)
dfmax

['datos\\semestre1c.csv', 'datos\\semestre2c.csv', 'datos\\semestre3c.csv']

   NOMBRE  APELLIDO  CALIFICACION      CARRERA  CIUDAD
0  ISMAEL    LOZANO            98  MECATRONICA  MERIDA
3   ANGEL  MORCILLO            98  MECATRONICA  MERIDA
2    RICK   SANCHEZ           100       FISICA  MERIDA

In [68]:
# establecer ruta de búsqueda  
# aquí queremos buscar archivos csv  
path = 'datos'
files = glob.glob(path + '/semestre?c.csv')
print(files)
list_filesmin = [] 
for file in files:
    temp_df = pd.read_csv(file)
    min_cal= temp_df.sort_values(by='CALIFICACION', ascending=True).head(1)
    list_filesmin.append(min_cal)
dfmin = pd.concat(list_filesmin, axis=0)
dfmin

['datos\\semestre1c.csv', 'datos\\semestre2c.csv', 'datos\\semestre3c.csv']

     NOMBRE   APELLIDO  CALIFICACION      CARRERA  CIUDAD
10      ANA    NAVARRO            59  MECATRONICA  MERIDA
6   VICENTE  CABALLERO             8  MECATRONICA  MERIDA
0    ISABEL       RUIZ            89  MECATRONICA  MERIDA

<div class="alert alert-success">
<b>EJERCICIO 4: Concatenar todos los archivos .csv de los semestres 2 y 3  </b>:

 <ul>
  <li> a) Encontrar el promedio y   desviación estándar  </li>
  <li> b) Datos del estudiante(s) con la calificación más alta </li>   
  <li> c) Datos del estudiante(s) con la calificación más baja </li>   
</ul>
</div>

In [69]:
 path = 'datos'
files = glob.glob(path + '/semestre[2-3]*.csv') #The "[]" for a range of number if in the files name have a number of interes 
print(files)
list_files = []
for file in files:
    temp_df = pd.read_csv(file)
    list_files.append(temp_df)
# concatenación
df = pd.concat(list_files, axis=0)
df

['datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre2c.csv', 'datos\\semestre3a.csv', 'datos\\semestre3b.csv', 'datos\\semestre3c.csv']

     NOMBRE   APELLIDO  CALIFICACION      CARRERA    CIUDAD
0  CONSUELO       PECH            83   RENOVABLES    MERIDA
1     ELENA   CASTILLO            73  MECATRONICA    MERIDA
2    JAVIER      PEREZ            57   RENOVABLES    MERIDA
3   ANGELES       DIAZ            80  MECATRONICA    MERIDA
4     MARIO    RAMIREZ            89       FISICA    MERIDA
5     PILAR    SERRANO            87   RENOVABLES   KANASIN
6    MIGUEL    JIMENEZ            80   RENOVABLES    MERIDA
0      ROSA   MORCILLO            93  MECATRONICA    MERIDA
1      JUAN     ARENAS            47       FISICA    MERIDA
2    DANIEL     ROMERO            98   RENOVABLES    MERIDA
3    RAFAEL        MAY            87  MECATRONICA    MERIDA
4     PABLO     MOLINA            86  MECATRONICA    MERIDA
5     MARIA      MARIN            86       FISICA    MERIDA
6     MARIA     GARCIA            96       FISICA    MERIDA
0    ALVARO      ORTIZ            89  MECATRONICA    MERIDA
1    ISABEL    SANCHEZ            96   RENOVABLES    MERIDA
2       ANA    ALARCON            84       FISICA  PROGRESO
3     ANGEL   MORCILLO            98  MECATRONICA    MERIDA
4     JESUS     ORTEGA            74  MECATRONICA    MERIDA
5     RAMON    GARRIDO            87  MECATRONICA     MOTUL
6   VICENTE  CABALLERO             8  MECATRONICA    MERIDA
0      JUAN    CEBRIAN            85       FISICA    MERIDA
1      JOSE    COLLADO            96       FISICA  PROGRESO
2   ANTONIA  RODRIGUEZ            83   RENOVABLES    MERIDA
3      LUIS      PEREZ            70  MECATRONICA     MOTUL
4  FERNANDO    CAMACHO            90   RENOVABLES    MERIDA
0    EMILIO      BALAM            85       FISICA    MERIDA
1     JULIA    RODENAS            98       FISICA    MERIDA
2    DANIEL        MAY            98   RENOVABLES    MERIDA
3     RAMON        MAY            87  MECATRONICA    MERIDA
4     PEDRO     MOLINA            96  MECATRONICA    MERIDA
5     LUCIA   MARTINEZ            86       FISICA    MERIDA
0    ISABEL       RUIZ            89  MECATRONICA    MERIDA
1    MARTIN       CANO            99       FISICA     TICUL
2      RICK    SANCHEZ           100       FISICA    MERIDA
3     CARLA   MORRISON            94       FISICA  PROGRESO
4     PEDRO      MARIN            98  MECATRONICA    MERIDA

In [70]:
print(df['CALIFICACION'].mean())
print(df['CALIFICACION'].std())

84.64864864864865
17.230812543258107

In [71]:
path = 'datos'
files = glob.glob(path + '/semestre[2-3]*.csv')
print(files)
list_filesmax = [] 
for file in files:
    temp_df = pd.read_csv(file)
    max_cal= temp_df.sort_values(by='CALIFICACION', ascending=False).head(1)
    list_filesmax.append(max_cal)
dfmax = pd.concat(list_filesmax, axis=0)
dfmax

['datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre2c.csv', 'datos\\semestre3a.csv', 'datos\\semestre3b.csv', 'datos\\semestre3c.csv']

   NOMBRE  APELLIDO  CALIFICACION      CARRERA    CIUDAD
4   MARIO   RAMIREZ            89       FISICA    MERIDA
2  DANIEL    ROMERO            98   RENOVABLES    MERIDA
3   ANGEL  MORCILLO            98  MECATRONICA    MERIDA
1    JOSE   COLLADO            96       FISICA  PROGRESO
1   JULIA   RODENAS            98       FISICA    MERIDA
2    RICK   SANCHEZ           100       FISICA    MERIDA

In [72]:
path = 'datos'
files = glob.glob(path + '/semestre[2-3]*.csv')
print(files)
list_filesmin = [] 
for file in files:
    temp_df = pd.read_csv(file)
    min_cal= temp_df.sort_values(by='CALIFICACION', ascending=True).head(1)
    list_filesmin.append(min_cal)
dfmin = pd.concat(list_filesmin, axis=0)
dfmin

['datos\\semestre2a.csv', 'datos\\semestre2b.csv', 'datos\\semestre2c.csv', 'datos\\semestre3a.csv', 'datos\\semestre3b.csv', 'datos\\semestre3c.csv']

    NOMBRE   APELLIDO  CALIFICACION      CARRERA  CIUDAD
2   JAVIER      PEREZ            57   RENOVABLES  MERIDA
1     JUAN     ARENAS            47       FISICA  MERIDA
6  VICENTE  CABALLERO             8  MECATRONICA  MERIDA
3     LUIS      PEREZ            70  MECATRONICA   MOTUL
0   EMILIO      BALAM            85       FISICA  MERIDA
0   ISABEL       RUIZ            89  MECATRONICA  MERIDA